java_test(
    name = "tests",
    size = "small",
    srcs = glob(["*.java"]),
    deps = [
        "//flagz-java/src/main/java/org/flagz",
        "//flagz-java/src/test/java/org/flagz/testclasses",
        "//third_party/guava",
        "//third_party/testing",
    ],
)
