dist: xenial


jdk:
  - oraclejdk8

env:
  - BAZEL_VERSION=0.3.2

addons:
  apt:
    packages:
      - wget

before_install:
  - wget "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
  - chmod +x bazel_${BAZEL_VERSION}-linux-x86_64.deb
  - sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
  - mv .bazelrc .bazelrc.orig
  - cat .bazelrc.travis .bazelrc.orig > .bazelrc

script:
  - bazel test //...
